import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kreasi Advertising Bukittinggi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}  `}>
        {/* <Header /> */}
        {children}
        <div className="h-[31.25rem] w-[31.25rem] sm:w-[68.75rem] rounded-full bg-emerald-300 p-8 absolute top-[2rem] right-[3rem] md:right-[20rem] lg:right-[30rem] blur-[10rem]"></div>
        <div className="h-[31.25rem] w-[31.25rem] sm:w-[68.75rem] rounded-full bg-pink-300 p-8 absolute top-[2rem] left-[3rem] md:left-[20rem] lg:right-[30rem] blur-[10rem]"></div>
      </body>
    </html>
  );
}
